// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdb9Q37SLtW0rf0n6KSZZg3t8lkzQDRGg',
    appId: '1:256890663703:web:2bb980a750737a39277d52',
    messagingSenderId: '256890663703',
    projectId: 'customerservicescheduler',
    authDomain: 'customerservicescheduler.firebaseapp.com',
    storageBucket: 'customerservicescheduler.appspot.com',
    measurementId: 'G-LSFJR9Y1CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpd84xqRqpd_jm2lujkMiqIi8xfNa6Ps',
    appId: '1:256890663703:android:64e94d0b7a613ae2277d52',
    messagingSenderId: '256890663703',
    projectId: 'customerservicescheduler',
    storageBucket: 'customerservicescheduler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMTst6XgLUA6gs3qjJp6etdKeRZoJxe88',
    appId: '1:256890663703:ios:5af6d41c8dcf88a6277d52',
    messagingSenderId: '256890663703',
    projectId: 'customerservicescheduler',
    storageBucket: 'customerservicescheduler.appspot.com',
    iosClientId: '256890663703-nlqghofjrrkjcqa8ueuj13scti7c2t2j.apps.googleusercontent.com',
    iosBundleId: 'com.customerservicescheduler.app',
  );
}
